### ISSUE TITLE
Functions that require a colon aren't callable

### ISSUE THREAD

**Issue by raymonable** [headsmasher8557/tpscript#6]
there's no way to call functions that require a colon
just try to `owner.Character:Destroy()`, it's impossible
i have no fucking clue how this could be fixed to be quite honest

(i apologize for being a nuisance but i have a LOT of interest in this project for some reason)

**Comment by headsmasher8557** [comment]
you CAN call functions that require a colon
just pass self to it
```
call owner.Character.Destroy owner.Character
```

**Comment by raymonable** [comment]
ohhh ok
